
services:

  postgres:
    build: .
    container_name: happy-block-db
    restart: always
    environment:
      POSTGRES_DB: happy_db
      POSTGRES_USER: happy_s
      POSTGRES_PASSWORD: 'h@pp1_d8'
    ports:
      - "5433:5432"
    networks:
      - happy-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  happy-block:
    build: .
    container_name: happy-block-app
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/happy_db?currentSchema=happy_db
      SPRING_DATASOURCE_USERNAME: happy_s
      SPRING_DATASOURCE_PASSWORD: 'h@pp1_d8'
    networks:
      - happy-network


networks:
  happy-network:

volumes:
  pgdata:
