spring:
  application:
    name: happy-block
    version: '@pom.version@'
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/happy_db?currentSchema=happy_db
    username: happy_s
    password: 'h@pp1_d8'
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true

happy:
  node:
    node-host: localhost
    node-port: 8545
  wallet:
    directory: "./wallet"
  encrypt:
    encryption-key: "wr%$^safl;j_safhsdfcv"

logging:
  level:
    root: INFO
    com.happy.block: DEBUG
    org.springframework: INFO
    org.web3j.protocol.http: DEBUG