spring:
  application:
    name: happy-block
    version: '@pom.version@'
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/happy_db?currentSchema=happy_db
    username: happy_s
    password: 'h@pp1_d8'
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true

